defaults: &defaults
  working_directory: ~/emotion-ts-plugin
  docker:
    - image: circleci/node:12-browsers

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run: echo 'export PATH=${PATH}:${HOME}/${CIRCLE_PROJECT_REPONAME}/node_modules/.bin' >> $BASH_ENV
      - run: curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
      - run: sudo ln -sf ~/.yarn/bin/yarn /usr/local/bin/yarn
      - restore_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: yarn
          command: |
            yarn
      - save_cache:
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build
      - persist_to_workspace:
          root: ~/emotion-ts-plugin
          paths:
            - ./*
  test:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/emotion-ts-plugin
      - run: yarn lint
      - run: yarn test
      - run:
          name: report-coverage
          command: npx codecov

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/emotion-ts-plugin
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: |
          if git log -1 --pretty=%B | grep "^[0-9]\+\.[0-9]\+\.[0-9]\+$";
          then
            npm publish
          else
            echo "Not a release, skipping publish"
          fi
workflows:
  version: 2
  build_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /.*/
            branches:
              only: /^(master|v11)$/
